### ISSUE TITLE
YouTubeApi.java - the name must not be empty: null

### ISSUE THREAD

**Issue by paulvaskar** [youtube/yt-watchme#24]
Hello , 
YouTubeApi.java is throwing error (the name must not be empty: null) when I am trying to execute 
LiveBroadcast returnedBroadcast = liveBroadcastInsert.execute(); 

Please suggest how to resolve the issue.

Thanks

**Comment by rzabangash** [comment]
add account from menu button , that will fix it..

**Comment by paulvaskar** [comment]
Thanks rzabangash, yes I resolved it. Now the only problem I am facing is I could only stream video, not the audio. I have compiled the ffameg using ndk, but could not stream the audio. please help me to resolve the audio issue.
Thanks

**Comment by rzabangash** [comment]
I have not tried this but you may check this https://github.com/youtube/yt-watchme/issues/23 and specially GavinCaptain answer, he have solved this problem..

**Comment by tuandnse02939** [comment]
@rzabangash Hi sir, how to add account from menu button? Can u describe it clearly? Tks so much

**Comment by achinverma** [comment]
Hello ,

I am getting the following error while trying to start live streaming using YouTube live streaming API form my android application. Please help me to resolve the issue.

Cannot open connection tcp://a.rtmp.youtube.com:1935

06-15 20:11:54.863 2109-2109/com.happytv.mobapp I/ffmpeg-jni﹕ ERROR: Could not open file rtmp://a.rtmp.youtube.com/live2/............

Ffmpeg.init() returned false

{
	"code": 403,
	"errors": [{
		"domain": "youtube.liveBroadcast",
		"message": "Stream is inactive",
		"reason": "errorStreamInactive",
		"extendedHelp": "https://developers.google.com/youtube/v3/live/docs/liveBroadcasts/transition"
	}],
	"message": "Stream is inactive"
}

**Comment by positivelymade** [comment]
@rzabangash Hi sir, how to add account from menu button? I would also like to know what you meant here.

**Comment by deryfath** [comment]
I got error like this when createBroadcast, anyone can help me?

Throwable: null
java.lang.IllegalArgumentException
    at com.google.api.client.repackaged.com.google.common.base.Preconditions.checkArgument(Preconditions.java:76)
    at com.google.api.client.util.Preconditions.checkArgument(Preconditions.java:37)
    at com.google.api.client.googleapis.auth.oauth2.GoogleClientSecrets.getDetails(GoogleClientSecrets.java:82)
    at com.google.api.services.samples.youtube.cmdline.Auth.authorize(Auth.java:55)
    at com.google.api.services.samples.youtube.cmdline.live.CreateBroadcast.main(CreateBroadcast.java:55)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
