### ISSUE TITLE
 java.lang.UnsatisfiedLinkError .android.apps.watchme.Ffmpeg.init

### ISSUE THREAD

**Issue by achinverma** [youtube/yt-watchme#34]
Hi , i am using this api for live streaming , but i am getting the below error when i try to create the Live stream

**java.lang.UnsatisfiedLinkError: No implementation found for boolean com.google.android.apps.watchme.Ffmpeg.init(int, int, int, java.lang.String) (tried Java_com_google_android_apps_watchme_Ffmpeg_init and Java_com_google_android_apps_watchme_Ffmpeg_init__IIILjava_lang_String_2)
            at com.google.android.apps.watchme.Ffmpeg.init(Native Method)
            at com.google.android.apps.watchme.VideoStreamingConnection.open(VideoStreamingConnection.java:71)
            at com.google.android.apps.watchme.StreamerService.startStreaming(StreamerService.java:72)
            at com.google.android.apps.watchme.StreamerActivity.startStreaming(StreamerActivity.java:210)
            at com.google.android.apps.watchme.StreamerActivity.access$200(StreamerActivity.java:47)
            at com.google.android.apps.watchme.StreamerActivity$1.onServiceConnected(StreamerActivity.java:67)
            at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1208)
            at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1225)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5343)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)**

![screencapture_2016-03-07_11 26 03](https://cloud.githubusercontent.com/assets/2811593/13561890/137213de-e458-11e5-9cc6-6114b8f4e8fc.png)

and Cannot resolve corresponding JNI function Java_com_google_android_apps_watchme_Ffmpeg_init less.
Reports native method declarations in Java where no corresponding JNI function is found in the project.

![screencapture_2016-03-07_12 14 06](https://cloud.githubusercontent.com/assets/2811593/13562453/d50738a2-e45e-11e5-88cb-f7c7a766da75.png)

**Comment by Sasha9132** [comment]
I have the same problem too
<img width="1423" alt="screen shot 2016-03-15 at 10 53 29" src="https://cloud.githubusercontent.com/assets/8059332/13772357/505a3502-ea9c-11e5-90b9-f9bffa2838a6.png">

**Comment by ghost** [comment]
I have the same issue but there is no result for this problem

**Comment by ghost** [comment]
package com.google.android.apps.watchme;

/**
- @author Ibrahim Ulukaya ulukaya@google.com
-         <p/>
- ```
      FFmpeg class which loads ffmpeg library and exposes its methods.
  ```
  
  */
  public class Ffmpeg {
  
  static {
      System.loadLibrary("ffmpeg-jni");
  }
  
  public static native boolean init(int width, int height, int audio_sample_rate, String rtmpUrl);
  
  public static native void shutdown();
  
  // Returns the size of the encoded frame.
  public static native int encodeVideoFrame(byte[] yuv_image);
  
  public static native int encodeAudioFrame(short[] audio_data, int length);
  }

And issue is 
No implementation found for boolean com.google.android.apps.watchme.Ffmpeg.init(int, int, int, java.lang.String) (tried Java_com_google_android_apps_watchme_Ffmpeg_init and Java_com_google_android_apps_watchme_Ffmpeg_init__IIILjava_lang_String_2)
06-24 18:13:03.799 18828-18828/com.google.android.apps.watchme D/AndroidRuntime: Shutting down VM
06-24 18:13:03.801 18828-18828/com.google.android.apps.watchme E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                 Process: com.google.android.apps.watchme, PID: 18828
                                                                                 java.lang.UnsatisfiedLinkError: No implementation found for boolean com.google.android.apps.watchme.Ffmpeg.init(int, int, int, java.lang.String) (tried Java_com_google_android_apps_watchme_Ffmpeg_init and Java_com_google_android_apps_watchme_Ffmpeg_init__IIILjava_lang_String_2)
                                                                                     at com.google.android.apps.watchme.Ffmpeg.init(Native Method)
                                                                                     at com.google.android.apps.watchme.VideoStreamingConnection.open(VideoStreamingConnection.java:71)
                                                                                     at com.google.android.apps.watchme.StreamerService.startStreaming(StreamerService.java:72)
                                                                                     at com.google.android.apps.watchme.StreamerActivity.startStreaming(StreamerActivity.java:212)
                                                                                     at com.google.android.apps.watchme.StreamerActivity.access$200(StreamerActivity.java:47)
                                                                                     at com.google.android.apps.watchme.StreamerActivity$1.onServiceConnected(StreamerActivity.java:67)
                                                                                     at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1208)
                                                                                     at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1225)
                                                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                     at android.os.Looper.loop(Looper.java:135)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5343)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

**Comment by TestingRaj** [comment]
Hi @achinverma, @Rakeshincluso , and other i am currently facing the same issues and really struggling to find a fix for this. It would be of huge help if any of you could respond with a solutions or the direction that i am supposed to move in.

**Comment by ramjanbashashaik** [comment]
I am also facing this issue .please some one help me

**Comment by chiragdigi** [comment]
Same issues, can anyone help?
