### ISSUE TITLE
java.lang.UnsatisfiedLinkError .android.apps.watchme.Ffmpeg.init

### ISSUE THREAD

**Issue by TestingRaj** [youtube/yt-watchme#38]
Hi their , 
Upon implementing the api for live streaming I came across the following issue/ error would be of huge help if any of you could suggest me a solution.

java.lang.UnsatisfiedLinkError: No implementation found for boolean com.google.android.apps.watchme.Ffmpeg.init(int, int, int, java.lang.String) (tried Java_com_google_android_apps_watchme_Ffmpeg_init and Java_com_google_android_apps_watchme_Ffmpeg_init__IIILjava_lang_String_2)
at com.google.android.apps.watchme.Ffmpeg.init(Native Method)
at com.google.android.apps.watchme.VideoStreamingConnection.open(VideoStreamingConnection.java:71)
at com.google.android.apps.watchme.StreamerService.startStreaming(StreamerService.java:72)
at com.google.android.apps.watchme.StreamerActivity.startStreaming(StreamerActivity.java:210)
at com.google.android.apps.watchme.StreamerActivity.access$200(StreamerActivity.java:47)
at com.google.android.apps.watchme.StreamerActivity$1.onServiceConnected(StreamerActivity.java:67)
at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1208)
at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1225)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5343)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

![137213de-e458-11e5-9cc6-6114b8f4e8fc](https://cloud.githubusercontent.com/assets/22838431/19389470/d3916b00-9241-11e6-870b-3e1870f68e5e.png)

and Cannot resolve corresponding JNI function Java_com_google_android_apps_watchme_Ffmpeg_init less.
Reports native method declarations in Java where no corresponding JNI function is found in the project.

![d50738a2-e45e-11e5-88cb-f7c7a766da75](https://cloud.githubusercontent.com/assets/22838431/19389497/eba2060a-9241-11e6-9dd0-bbafb36289f6.png)

**Comment by abram456** [comment]
Same issue.... Can some one answer who got the solution

**Comment by ntanduc2288** [comment]
I'm facing the same issue...I think the root cause is libffmpeg.so which downloaded from internet (yt-watchme project have no libffmpeg.so)

**Comment by MuthuEphron** [comment]
I got  the same issue . Any solution for this issues

**Comment by TestingRaj** [comment]
Hi

you can use below link here is my complete project

https://www.dropbox.com/s/yshwhmlhg02zaqf/MainActivity.zip?dl=0

**Comment by MuthuEphron** [comment]
Hi 
I am working in windows 10 and android studio 2.1.2.
Is your project working in Windows?

**Comment by TestingRaj** [comment]
yeah this code is working in windows

**Comment by MuthuEphron** [comment]
Are you used android studio ?

**Comment by TestingRaj** [comment]
no this code used in eclipse you can copy only library

**Comment by TestingRaj** [comment]
After that i changed the code eclipse to android studio that time also i
copied only lib and refere below screen shot

[image: Inline image 1]

**Comment by MuthuEphron** [comment]
Sorry, I didn't get your screenshot.

**Comment by MuthuEphron** [comment]
because I  got the error in build to gradle.

**Comment by TestingRaj** [comment]
can u send me ur mail id

**Comment by MuthuEphron** [comment]
Hi TestingRaj,

Here I attached build.gradle,

Actually My Error is
java.lang.UnsatisfiedLinkError: Couldn't load ffmpeg library findLibrary
returned null
<http://stackoverflow.com/questions/42395461/java-lang-unsatisfiedlinkerror-couldnt-load-ffmpeg-library-findlibrary-returne>

**Comment by TestingRaj** [comment]
u changed package name you need to give same package name in watch me
application because these lib are already compiled if you want to give ur
package name then u need to confihure JNI and create your package name all
library in file JNI folder

**Comment by MuthuEphron** [comment]
Pls send  my  mail id muthuephron39@gmail.com

**Comment by MuthuEphron** [comment]
Thanks for your help. Please check my gradle is there any mistakes in my gradle and Android.mk. Application.mk,config file also.

**Comment by MuthuEphron** [comment]
I need to know how to use my project.

**Comment by MuthuEphron** [comment]
@TestingRaj  I  setup library load ffmpeg.so file but now the  issue was "Java.Lang.unsatisfiedLinkerror Native method not found error in my Project , Please help related issues in ffmpeg. 
I need another one how to use FFmpeg -jni,c file  in my project?

**Comment by vranacse** [comment]
need working demo app with both video and audio working ! contact : vranacse@gmail.com

**Comment by MuthuEphron** [comment]
@TestingRaj  Hi i am using your code but its not working on windows. because  you declare the android.mk path is invalid

**Comment by jeff11142** [comment]
I need help too , my Email is doggy90739@gmail.com
I tried lots of ways but i still cant build it up

**Comment by MuthuEphron** [comment]
Hi guys, 
Pleas help this issues #53

**Comment by MuthuEphron** [comment]
@TestingRaj Audio issues is present on live streaming video. How  do solve the issue  Please Help.

**Comment by MuthuEphron** [comment]
@TestingRaj  How to use third party folder in android studio

**Comment by prabhanshushekharntspl** [comment]
@TestingRaj 
 I have downloaded the file from "https://www.dropbox.com/s/yshwhmlhg02zaqf/MainActivity.zip?dl=0" but the file is not working in android studio. Please send me the solution.
Email id : prabhanshu.sekhar@ntspl.co.in

**Comment by Adnan-addi** [comment]
Does anyone Got the Solution for this .. in 2019 ???

**Comment by garyjamessilva** [comment]
Yeah just learn basic android jni / c function naming and calling and the
issues / solution is obvious.

Good luck
