### ISSUE TITLE
Unfortunately, youtube watchme has stopped.

### ISSUE THREAD

**Issue by abram456** [youtube/yt-watchme#41]
This is the log and can some one help me out.

10-26 16:26:26.820 15200-15235/com.google.android.apps.watchme W/MALI: glDrawArrays:714: [MALI] glDrawArrays takes more than 5ms here. Total elapse time(us): 7016
10-26 16:26:26.875 15200-15200/com.google.android.apps.watchme E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                 Process: com.google.android.apps.watchme, PID: 15200
                                                                                 java.lang.NoSuchMethodError: No virtual method checkSelfPermission(Ljava/lang/String;)I in class Lcom/google/android/apps/watchme/StreamerActivity; or its super classes (declaration of 'com.google.android.apps.watchme.StreamerActivity' appears in /data/data/com.google.android.apps.watchme/files/instant-run/dex/slice-slice_2-classes.dex)
                                                                                     at com.google.android.apps.watchme.StreamerActivity.startStreaming(StreamerActivity.java:174)
                                                                                     at com.google.android.apps.watchme.StreamerActivity.access$200(StreamerActivity.java:46)
                                                                                     at com.google.android.apps.watchme.StreamerActivity$1.onServiceConnected(StreamerActivity.java:66)
                                                                                     at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1266)
                                                                                     at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1283)
                                                                                     at android.os.Handler.handleCallback(Handler.java:815)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                                     at android.os.Looper.loop(Looper.java:194)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5706)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1033)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:828)
10-26 16:26:44.008 15200-15318/com.google.android.apps.watchme E/WatchMe: com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
                                                                          {
                                                                            "code": 403,
                                                                            "errors": [
                                                                              {
                                                                                "domain": "youtube.liveBroadcast",
                                                                                "message": "Stream is inactive",
                                                                                "reason": "errorStreamInactive",
                                                                                "extendedHelp": "https://developers.google.com/youtube/v3/live/docs/liveBroadcasts/transition"
                                                                              }
                                                                            ],
                                                                            "message": "Stream is inactive"
                                                                          }
                                                                              at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
                                                                              at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
                                                                              at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:321)
                                                                              at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1065)
                                                                              at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
                                                                              at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
                                                                              at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
                                                                              at com.google.android.apps.watchme.util.YouTubeApi.startEvent(YouTubeApi.java:187)
                                                                              at com.google.android.apps.watchme.MainActivity$StartEventTask.doInBackground(MainActivity.java:386)
                                                                              at com.google.android.apps.watchme.MainActivity$StartEventTask.doInBackground(MainActivity.java:371)
                                                                              at android.os.AsyncTask$2.call(AsyncTask.java:292)
                                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                              at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                              at java.lang.Thread.run(Thread.java:818)

**Comment by abram456** [comment]
Answer is at [(https://github.com/youtube/yt-watchme/issues/25)]

**Comment by MuthuEphron** [comment]
Please help me. I am working youtube watch me project in Android studio in Windows 10. I got the error
## " java.lang.UnsatisfiedLinkError: No implementation found for int com.ephronsystem.mobilizerapp.Ffmpeg.encodeVideoFrame(byte[]) (tried Java_com_ephronsystem_mobilizerapp_Ffmpeg_encodeVideoFrame and Java_com_ephronsystem_mobilizerapp_Ffmpeg_encodeVideoFrame___3B)" #
