### ISSUE TITLE
FATAL EXCEPTION, when I select event

### ISSUE THREAD

**Issue by abram456** [youtube/yt-watchme#42]
This is the log I got, Can some help me out?

10-26 19:05:59.160 31881-31881/com.google.android.apps.watchme E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                 Process: com.google.android.apps.watchme, PID: 31881
                                                                                 java.lang.NoSuchMethodError: No virtual method checkSelfPermission(Ljava/lang/String;)I in class Lcom/google/android/apps/watchme/StreamerActivity; or its super classes (declaration of 'com.google.android.apps.watchme.StreamerActivity' appears in /data/data/com.google.android.apps.watchme/files/instant-run/dex/slice-slice_2-classes.dex)
                                                                                     at com.google.android.apps.watchme.StreamerActivity.startStreaming(StreamerActivity.java:174)
                                                                                     at com.google.android.apps.watchme.StreamerActivity.access$200(StreamerActivity.java:46)
                                                                                     at com.google.android.apps.watchme.StreamerActivity$1.onServiceConnected(StreamerActivity.java:66)
                                                                                     at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1266)
                                                                                     at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1283)
                                                                                     at android.os.Handler.handleCallback(Handler.java:815)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                                     at android.os.Looper.loop(Looper.java:194)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5706)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1033)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:828)

**Comment by abram456** [comment]
@ymotongpoo @libor
