### ISSUE TITLE
Camera is deprecated in android 6.0

### ISSUE THREAD

**Issue by bharathcd** [youtube/yt-watchme#48]
Camera is deprecated in android 6.0. I had a issue when I run the application android 6.0 devices. I have received below exception with I open the event, 

```
 java.lang.NullPointerException: Attempt to invoke virtual method 'android.hardware.Camera$Parameters android.hardware.Camera.getParameters()' on a null object reference
                                                     at com.google.android.apps.watchme.VideoFrameGrabber.start(VideoFrameGrabber.java:44)
                                                     at com.google.android.apps.watchme.VideoStreamingConnection.open(VideoStreamingConnection.java:66)
                                                     at com.google.android.apps.watchme.StreamerService.startStreaming(StreamerService.java:72)
                                                     at com.google.android.apps.watchme.StreamerActivity.startStreaming(StreamerActivity.java:211)
                                                     at com.google.android.apps.watchme.StreamerActivity.access$200(StreamerActivity.java:46)
                                                     at com.google.android.apps.watchme.StreamerActivity$1.onServiceConnected(StreamerActivity.java:66)
                                                     at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1223)
                                                     at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1240)
                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:148)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

How to fix this issue?

**Comment by MuthuEphron** [comment]
Hi guys, 
Pleas help this issues #53
